// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SampleBrowser.iOS
{
	public partial class DynamicLaunchScreenViewController : UIViewController
	{
		public DynamicLaunchScreenViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
